# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
##

name: Java CI with Maven

on:
  push:
    branches: [ maven-experimental ]
  pull_request:
    branches: [ maven-experimental ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java JDk
        uses: actions/setup-java@v1.4.3
        with:
          java-version: '14' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Build with Maven
        run: mvn -B package --file pom.xml
